---

- name: Basic setup
  hosts: raspberries
  become: yes
  tasks:
    # Update system
    - name: Update apt
      apt:
        update_cache: true

    - name: Upgrade all packages
      apt:
        upgrade: dist

    # Configure SSH daemon for security
    - name: Configure secure SSH configuration
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no' } 
        - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
        - { regexp: '^#?MaxAuthTries', line: 'MaxAuthTries 3' }
        - { regexp: '^#?X11Forwarding', line: 'X11Forwarding no' }
        - { regexp: '^#?UsePAM', line: 'UsePAM no' }
        - { regexp: '^#?AllowTcpForwarding', line: 'AllowTcpForwarding no' }
        - { regexp: '^#?AllowAgentForwarding', line: 'AllowAgentForwarding no' }
        - { regexp: '^#?PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
      notify: restart ssh

    - name: Install security packages
      apt:
        name:
          - fail2ban
          - ufw
          - unattended-upgrades
        state: present

    - name: Install application packages
      apt:
        name:
          - cockpit
          - rsync
          - wireguard
        state: present

    - name: Create fail2ban jail.local file
      copy:
        dest: /etc/fail2ban/jail.local
        src: ./files/fail2ban/jail.local
    
    - name: Enable fail2ban
      service:
        name: fail2ban
        state: started
        enabled: yes
    
    - name: Allow SSH through UFW
      ufw:
        rule: allow
        name: OpenSSH
        state: enabled

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny

    - name: Enable automatic updates
      debconf:
        name: unattended-upgrades
        question: unattended-upgrades/enable_auto_updates
        value: "true"
        vtype: boolean

    # Configure unattended-upgrades behavior
    - name: Configure unattended-upgrades
      blockinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        create: yes
        block: |
          Unattended-Upgrade::Allowed-Origins {
              "${distro_id}:${distro_codename}";
              "${distro_id}:${distro_codename}-security";
              "${distro_id}ESMApps:${distro_codename}-apps-security";
              "${distro_id}ESM:${distro_codename}-infra-security";
          };
          Unattended-Upgrade::AutoFixInterruptedDpkg "true";  # Fix interrupted upgrades
          Unattended-Upgrade::MinimalSteps "true";            # Use minimal steps
          Unattended-Upgrade::InstallOnShutdown "false";      # Don't install on shutdown
          Unattended-Upgrade::Remove-Unused-Dependencies "true";  # Clean up
          Unattended-Upgrade::Automatic-Reboot "false";       # Don't reboot automatically
    
    # Configure automatic update schedule
    - name: Configure automatic updates
      copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        src: ./files/apt/20auto-upgrades

    - name: Start and enable unattended-upgrades service
      service:
        name: unattended-upgrades
        state: started
        enabled: yes

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted
...